unit TestBlockingCollection1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, GpStuff, Windows, DSiWin32, OtlContainers, SysUtils,
  OtlContainerObserver, OtlCollections, OtlCommon, OtlSync;

type
  // Test methods for class IOmniBlockingCollection
  TestIOmniBlockingCollection = class(TTestCase)
  strict private
    FIOmniBlockingCollection: IOmniBlockingCollection;
  public
  published
    procedure TestCompleteAdding;
  end;

implementation

procedure TestIOmniBlockingCollection.TestCompleteAdding;
begin
  FIOmniBlockingCollection.CompleteAdding;
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestIOmniBlockingCollection.Suite);
end.

